# <head> 里面的 baseurl 信息，填你的博客地址
baseURL = "http://49.235.231.121/" 

# 浏览器的标题
title = "SilenceHL Blog" 

# 描述
description = "胡亮的个人技术博客网站"

# 语言
languageCode = "zh-cn"

# 开启可以让「字数统计」统计汉字
hasCJKLanguage = true

# 主题 (需要自己下载)
theme = "LeaveIt"

# 每页的文章数

paginate = 100

# 支持 Emoji
enableEmoji = true

# 支持 robots.txt
enableRobotsTXT = true

# Google 统计 id
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
    since = 2019
    author = "SilenceHL"                          # Author's name
    avatar = "https://tva1.sinaimg.cn/large/006lmzsGgy1gap3env4c4j30hs0hsglu.jpg"           # Author's avatar
    subtitle = "Life is too short"                  # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other
    enableGitalk = true # gitalk 评论系统

    google_verification = ""
    description = "" # (Meta) 描述
    keywords = "" # site keywords
    beian = ""
    baiduAnalytics = ""
    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'


[params.social]
    GitHub = "Silencehuliang"
    Twitter = "fMDWkocsPkSZY0F"
    Email   = "silencehuliang@gmail.com"
    # Instagram = "xxoo"
    Wechat = "https://tvax4.sinaimg.cn/large/006lmzsGgy1gauoevudltj30by0by3yw.jpg"  # Wechat QRcode image
    Facebook = "silencehuliang"
    # Telegram = "xxoo"
    # Dribbble = "xxoo"
    # Medium = "xxoo"

 # Valine.
 # You can get your appid and appkey from https://leancloud.cn
 # more info please open https://valine.js.org
[params.valine]
    enable = true
    appId = 'CPUadU9FrUpQzf7dYqNF9gbT-gzGzoHsz'
    appKey = 'fsddpUyXPG7Nsn65o5bdydWH'
    notify = true  # mail notifier , https://github.com/xCss/Valine/wiki
    verify = false # Verification code
    avatar = 'mp'
    placeholder = '说点什么吧...(邮箱不会显示,有回复可以收到提醒邮件!)'
    visitor = true
    meta = ['nick','mail']


# 是否开启目录
toc = true

# Auto expand and collapse toc
autoCollapseToc = true 

# 更准确的统计字数
hasCJKLanguage = true

enableDarkMode = true

defaultTheme = "dark"

hideThemeToggle = false

hideThemeToggleInHome = false
